### ISSUE TITLE
[DUPLICATE] connecting ... (no incomming video) StreamingDirectxClient problem

### ISSUE THREAD

**Issue by parandham03** [CatalystCode/3dtoolkit#168] opened 2018-04-10 11:49 UTC
When running StreamingDirectxClient and SpinningCubeServer i getting "connecting ... (no incomming video). Please help me solve the issue.

**Comment by bengreenier** [comment] 2018-04-10 15:03
Closing as this is a duplicate of https://github.com/CatalystCode/3dtoolkit/issues/161 - please see existing thread/required information for helping debug from that issue. Thanks 👍

**Closed by bengreenier** 2018-04-10 15:03 UTC
Labels: bug
