### ISSUE TITLE
UnityServer not connecting to Signalling 

### ISSUE THREAD

**Issue by korzen** [CatalystCode/3dtoolkit#135] opened 2017-11-09 09:37 UTC
Hi,

I have got all the various client/server combinations working except the UnityServer, which is actually the most important for us. I simply can't get the UnityServer (unmodified Fractal scene) to connect to signalling (neither local nor on Azure). The build starts without any problems, there are no errors in the log, i have got the fractal rendered and it only displays empty dropdown list and connect button. 

I can't debug it from the editor as it is crashing when I check UseEditorNativePlugin box.

Thanks

**Comment by phongcao** [comment] 2017-11-09 13:15
Are you using the **main_cloud** scene and setting the webrtcConfig file properly?

**Comment by korzen** [comment] 2017-11-09 13:18
Hi Phong Cao,

I am on the latest master so the only scene is StereoCapableFractalCubes. And yes, I am 100% that the webrtcConfig is fine, it is identical to the others I am using with non-Unity clients/servers and which connect just fine.

Cheers

**Comment by phongcao** [comment] 2017-11-09 13:33
Got you. I'll check and let you know.

**Comment by korzen** [comment] 2017-11-09 21:31
Hi @phongcao, did you manage to reproduce this problem?

**Comment by phongcao** [comment] 2017-11-09 22:13
Yes, it's working for me. Also you should try the latest branch having image stabilization:
https://github.com/CatalystCode/3dtoolkit/pull/133

Currently I'm still trying to do some more optimization for the Unity FractalStream server but it's working pretty well now. Please follow these steps:

1. Get the latest updates from _enhancement/image-stabilization_ branch.
2. Building **StreamingUnityServerPlugin.sln** (x64 Release).
3. Building **Unity-FractalStream** sample in Unity editor (choose x86_64 setting).
4. Changing **VIDEO_FRAME_WIDTH** and **VIDEO_FRAME_HEIGHT** to **1280x600** (these params need to match the window size of the server later) and building **StreamingDirectxClientHololens.sln** (x86 Release).
5. Running the server app with **-force-d3d11-no-singlethreaded** flag. Then set the window size to **1280x600**.
6. Running the DirectX client. From the server window, choose to connect to that HoloLens client.

Let me know if it works for you.

**Comment by phongcao** [comment] 2017-11-12 20:24
@korzen The Unity FractalStream server should work well now.

**Comment by korzen** [comment] 2017-11-13 16:14
Thanks @phongcao, I am on short holidays, will give it a try next monday.

Cheers

**Comment by korzen** [comment] 2017-11-27 14:38
Hi @phongcao ,

I have just tried the latest master (x64) as well as ImageStabilization (x86) branches and I still can't connect the UnityServer to Signalling. I made a short video to visualise the problem [https://youtu.be/EXVF7d6bipI](https://youtu.be/EXVF7d6bipI)

I have also attached the log
[output_log.txt](https://github.com/CatalystCode/3dtoolkit/files/1506145/output_log.txt)

Thanks again for looking at it.

Cheers

**Comment by phongcao** [comment] 2017-11-27 19:27
@korzen I couldn't find anything wrong with your setup. Don't know why the Fractal stream server can't connect to the local signaling server while the spinning cube/multithreaded ones can.
@bengreenier Can you tell korzen how to enable the WebRTCServer debug script so that we can collect more logs?

**Comment by bengreenier** [comment] 2017-11-27 20:18
@korzen adding `-webrtc-debug-log` to the command line arguments should inject additional logging data into output_log.txt - give that a shot and link us the results - I can't think of a quick reason this isn't working as expected, but that should give us something to investigate deeper 🐛 😕

**Comment by korzen** [comment] 2017-11-27 20:26
@bengreenier, I tried -webrtc-debug-log before:
[output_log.txt](https://github.com/CatalystCode/3dtoolkit/files/1507477/output_log.txt)

For some reason the server build is not listed in Visual Studio to attach the unity debugger to it. 
And when I check the UseEditorNativePlugin in the editor I get a crash on play.
I have "-force-d3d11-no-singlethreaded" on the Unity.exe, not sure though if this is the reason or if the flag is recognised at all by the editor

**Comment by bengreenier** [comment] 2017-11-27 20:40
Attaching the unity debugger will be tricky, you need to catch the application at just the right point - i added the `-webrtc-debug-sleep` option to try and help with that (it sleeps a number of milliseconds before continuing) you can try that. 

If you want to attach a regular old vs debugger and jump through the native code (this is probably the quickest way to a solution, but it's non-trivial), you can:

1) open the 3DStreamingToolkit.sln vs solution
2) start the server (do not click through the unity display/input popup)
3) in vs, do debug -> attach to process
4) find process
5) open [this file, set a breakpoint at this highlighted line](https://github.com/CatalystCode/3dtoolkit/blob/master/Plugins/UnityServerPlugin/StreamingUnityServerPlugin.cpp#L257)
6) return to the server window and click through the unity popup now
7) wait for breakpoint to hit
8) step forward in code and see what gets stuck

step 5 is determined from the above log entry `[2]: InitWebRTC`, which is directly correlated with the linked line. my guess is that something blows up in there and some error state isn't propagated back to the managed side properly.

@phongcao  - if that is the case i'll be sure we track that as a separate issue (we should surface this failure much more clearly).

**Comment by phongcao** [comment] 2017-11-27 23:25
@bengreenier Agree.
@korzen Could you please either put more **ULOG** inside **InitWebRTC** method or jump into that one with breakpoint debugger (following Ben's suggestion) and let us know where it crashes? It's difficult for us to understand about that failure since we can't reproduce it from our side.

**Comment by korzen** [comment] 2017-11-28 14:14
@phongcao @bengreenier I have tried the whole build and deploy from scratch on a fresh Win10 installation, fresh Unity 5.6.4 x64, VS 2015 and fresh master branch - same thing. 

I will debug the wrapper .dlls later today and let you know about the findings.

Cheers

**Comment by bengreenier** [comment] 2017-11-28 15:47
@korzen it's definitely possible that something is wrong on `master` - our testing suite is currently super primitive, so while i'd like to say i'm `100%` confident in that code, there is definitely a chance there's some conditions we didn't validate. I'm trying to repro this issue on my machine now and will follow up with the results.

**Comment by bengreenier** [comment] 2017-11-28 16:00
hmm - `master`, with the `3DStreamingToolkit.sln` built with `Debug` `x86` using `Unity 5.6.3f1 (x64)` exporting for `PC/Mac/Linux Standalone` with `Target Platform: Windows` and `Architecture: x86` and running with `-force-d3d11-no-singlethreaded -webrtc-debug-log` works on `win10 1709.16299.64`) on my end, so i can confirm no repro on my side at this point in time 😕

**Comment by bengreenier** [comment] 2017-11-28 16:04
actually - noticed our unity versions are different - since we're hooking on the graphics pipeline and there's some churn in `5.6` builds - can you try syncing to [this unity version](https://download.unity3d.com/download_unity/d3101c3b8468/Windows64EditorInstaller/UnitySetup64-5.6.3f1.exe)? If that solves the issue we'll need to follow up to support `5.6.4`, but it will at least explain the inability to repro.

**Comment by phongcao** [comment] 2017-11-28 16:07
@bengreenier korzen was using Unity 5.6.3f1 as shown in [output_log.txt](https://github.com/CatalystCode/3dtoolkit/files/1507477/output_log.txt).

**Comment by bengreenier** [comment] 2017-11-28 16:08
@phongcao  ah - was going off the comment [above](https://github.com/CatalystCode/3dtoolkit/issues/135#issuecomment-347535648) 😸

**Comment by phongcao** [comment] 2017-11-28 16:09
@korzen I remember that you used to be able to run the Unity FractalStream server before and suffered the latency issue. Is that right? Do you still remember which commit it is or try rolling back to some earlier commits to test?

**Comment by korzen** [comment] 2017-11-29 21:08
My apologies @phongcao and @bengreenier, 

I have made a debug build of the unity server plugin .dll and it turned out that the server is not connecting due to the authentication failure. I removed the corresponding entries in the webrtcConfig file and the server worked like a charm. I overlooked this as the previous versions I worked with were without the authentication.

Nevertheless, a "Authentication failed" in the output.log would be really helpful;)

Sorry again.

Please close the issue

**Comment by bengreenier** [comment] 2017-11-29 21:11
@korzen glad it worked out! 💯 

closing 😸

**Closed by bengreenier** 2017-11-29 21:11 UTC
Labels: bug, question
